{% set name = "morphometrics" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morphometrics-{{ version }}.tar.gz
  sha256: bec086a9c853da15350dba5b72a0bf00f27257878518c9aea8c9b7a6499914ca

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py==37]

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - cython
    - hdbscan
    - jinja2 >=2.10,<3.1
    - leidenalg
    - napari
    - napari-clusters-plotter
    - napari-skimage-regionprops
    - numba >=0.55.2
    - numpy <1.22
    - ocl-icd-system  # [linux]
    - ocl_icd_wrapper_apple  # [osx]
    - pandas
    - pyclesperanto-prototype >=0.8.0
    - pymeshfix
    - pyopencl
    - pytables
    - python
    - python-igraph
    - scanpy
    - scikit-image >0.19.0
    - scikit-learn >=0.24.2
    - tqdm
    - trimesh

test:
  imports:
    - morphometrics
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/morphometrics/morphometrics
  summary: A plugin for quantifying shape and neighborhoods from images.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kevinyamauchi
