{% set name = "morphometrics" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morphometrics-{{ version }}.tar.gz
  sha256: d4b803c3928806e0747a2ad4b64bc25cc65a0a5a096bfad3b947527d3d4896c8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py!=39]

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - cython
    - glasbey
    - hdbscan
    - imageio >=2.5.0,!=2.11.0,!=2.22.1
    - jinja2 >=2.10,<3.1
    - leidenalg
    - napari
    - napari-clusters-plotter
    - napari-skimage-regionprops
    - numba
    - numpy
    - ocl-icd-system  # [linux]
    - ocl_icd_wrapper_apple  # [osx]
    - pandas
    - pooch
    - pyclesperanto-prototype >=0.8.0
    - pymeshfix
    - pyopencl
    - pyqt >=5.12.3,!=5.15.0
    - pyqtgraph
    - pytables
    - python
    - python-igraph
    - scanpy
    - scikit-image >0.19.0
    - scikit-learn >=0.24.2
    - tqdm
    - trimesh

test:
  imports:
    - morphometrics
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/morphometrics/morphometrics
  summary: A plugin for quantifying shape and neighborhoods from images.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kevinyamauchi
